name: Checkout Setup Restore Build and Test

on:
  push:
    branches: 
    - develop
    - feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: 
       dotnet-version: 6.0.x
    - name: Restore the app dependencies
      run: dotnet restore
    - name: Build the app
      run: dotnet build --no-restore
    - name: Test the app
      run: dotnet test --no-build --verbosity normal
